FamilyExpenses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('home/', include('expense.urls')),
    path('incomes/', include('income.urls')),
    path('accounts/', include('accounts.urls')),
    path('preferences/', include('userperferences.urls')),
    path('admin/', admin.site.urls),


    # Password Logic
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include

from .views import RegisterView, UserLogin, UsernameValidationView, UserEmailValidationView, \
    UserFamilyValidationView, UserHeadValidationView, PasswordValidationView, LogoutView, password_reset_request
from django.views.decorators.csrf import csrf_exempt

app_name = "account"
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLogin.as_view(), name='login'),
    path('validate-username/', csrf_exempt(UsernameValidationView.as_view()), name='validate-username'),
    path('validate-email/', csrf_exempt(UserEmailValidationView.as_view()), name='validate-email'),
    path('validate-family-name/', csrf_exempt(UserFamilyValidationView.as_view()), name='validate-family-name'),
    path('validate-family-head/', csrf_exempt(UserHeadValidationView.as_view()), name='validate-family-head'),
    path('validate-password/', csrf_exempt(PasswordValidationView.as_view()), name='validate-password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("password_reset", password_reset_request, name="password_reset"),


]

expense/urls.py
from django.urls import path

from expense.views import delete_expense, ExpenseCreateView, ExpenseEditView, search_expenses, \
    MaterialCreateView, ExpenseListView, MaterialListView, MaterialEditView, delete_material, OutlayTypeListView, \
    OutlayTypeCreateView, OutlayTypeEditView, delete_outlaytype, UserListView, UserCreateView, ExpensesChartList
from django.views.decorators.csrf import csrf_exempt

app_name = "expenses-dash"
urlpatterns = [

    # Expense
    path('', ExpenseListView.as_view(), name='expenses'),
    path('search-expenses', csrf_exempt(search_expenses), name='search_expenses'),
    path('add-expense/', ExpenseCreateView.as_view(), name='add_expense'),
    path('edit-expense/<int:pk>', ExpenseEditView.as_view(), name='edit_expense'),
    path('delete-expense/<int:pk>', delete_expense, name='delete_expense'),

    # Materials
    path('materials/', MaterialListView.as_view(), name='materials'),
    path('add-material/', MaterialCreateView.as_view(), name='add_material'),
    path('edit-material/<int:pk>', MaterialEditView.as_view(), name='edit_material'),
    path('delete-material/<int:pk>', delete_material, name='delete_material'),

    # Outlay Types
    path('outlaytypes/', OutlayTypeListView.as_view(), name='outlaytypes'),
    path('add-outlaytype/', OutlayTypeCreateView.as_view(), name='add_outlaytype'),
    path('edit-outlaytype/<int:pk>', OutlayTypeEditView.as_view(), name='edit_outlaytype'),
    path('delete-outlaytypes/<int:pk>', delete_outlaytype, name='delete_outlaytype'),

    # User
    path('users/', UserListView.as_view(), name='users'),
    path('add-user/', UserCreateView.as_view(), name='add_user'),
    # path('edit-outlaytype/<int:pk>', OutlayTypeEditView.as_view(), name='edit_outlaytype'),

    # Chart
    path("expenses-chart-list/", ExpensesChartList.as_view(), name="export_pdf"),

]

income/urls.py
from django.urls import path

from income.views import IncomeListView, IncomeEditView, delete_income, IncomeCreateView

app_name = "income-dash"
urlpatterns = [

    # Expense
    path('', IncomeListView.as_view(), name='incomes'),
    path('add-income/', IncomeCreateView.as_view(), name='add_income'),
    path('edit-income/<int:pk>', IncomeEditView.as_view(), name='edit_income'),
    path('delete-income/<int:pk>', delete_income, name='delete_income'),
    ]

userperferences/urls.py
from django.urls import path

from .views import index

app_name = "preference"
urlpatterns = [
    path('', index, name='preferences'),

]

templates/partials/_messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-sm alert-{{ message.tags }}"{% endif %}>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

templates/partials/_sidebar.html
{% load static i18n %}
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home" class="align-text-bottom"></span>
              {% trans 'Dashboard' %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "expenses-dash:expenses" %}">

              {% trans 'Expenses' %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "income-dash:incomes" %}">
              {% trans 'Income' %}
            </a>
          </li>

        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
          <span>{% trans 'Summary' %}</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle" class="align-text-bottom"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="{% url "expenses-dash:export_pdf" %}">

              {% trans 'Expenses Summary' %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">

              {% trans 'Icomes Summary' %}
            </a>
          </li>

        </ul>


        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
          <span>{% trans 'DashBoard Control' %}</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle" class="align-text-bottom"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'expenses-dash:expenses' %}">

              {% trans 'Control Expenses' %}
            </a>
          </li>
            {% if request.user.is_head_of_fmaily %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'expenses-dash:materials' %}">

              {% trans 'Control Materials' %}
            </a>
          </li>
                          <li class="nav-item">
            <a class="nav-link" href="{% url 'expenses-dash:outlaytypes' %}">

              {% trans 'Control Outlay Types' %}
            </a>
          </li>
                                          <li class="nav-item">
            <a class="nav-link" href="{% url 'expenses-dash:users' %}">

              {% trans 'Control Users' %}
            </a>
          </li>

            {% endif %}
        </ul>

      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
          <span>{% trans 'Settings' %}</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle" class="align-text-bottom"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'preference:preferences' %}">

              {% trans 'General Settings' %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "account:logout" %}">{% trans 'Sign out' %}


            </a>
          </li>
        </ul>
      </div>
    </nav>