FamilyExpenses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('home/', include('expense.urls')),
    path('incomes/', include('income.urls')),
    path('accounts/', include('accounts.urls')),
    path('preferences/', include('userperferences.urls')),
    path('admin/', admin.site.urls),


    # Password Logic
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include

from .views import RegisterView, UserLogin, UsernameValidationView, UserEmailValidationView, \
    UserFamilyValidationView, UserHeadValidationView, PasswordValidationView, LogoutView, password_reset_request
from django.views.decorators.csrf import csrf_exempt

app_name = "account"
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLogin.as_view(), name='login'),
    path('validate-username/', csrf_exempt(UsernameValidationView.as_view()), name='validate-username'),
    path('validate-email/', csrf_exempt(UserEmailValidationView.as_view()), name='validate-email'),
    path('validate-family-name/', csrf_exempt(UserFamilyValidationView.as_view()), name='validate-family-name'),
    path('validate-family-head/', csrf_exempt(UserHeadValidationView.as_view()), name='validate-family-head'),
    path('validate-password/', csrf_exempt(PasswordValidationView.as_view()), name='validate-password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("password_reset", password_reset_request, name="password_reset"),


]

income/urls.py
from django.urls import path

from income.views import IncomeListView, IncomeEditView, delete_income, IncomeCreateView

app_name = "income-dash"
urlpatterns = [

    # Expense
    path('', IncomeListView.as_view(), name='incomes'),
    path('add-income/', IncomeCreateView.as_view(), name='add_income'),
    path('edit-income/<int:pk>', IncomeEditView.as_view(), name='edit_income'),
    path('delete-income/<int:pk>', delete_income, name='delete_income'),
    ]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class Family(models.Model):
    """ Family Model """
    family_name = models.CharField(_("Name of Family Name"), blank=True, max_length=255, unique=True)


class User(AbstractUser):
    """ Custom User Model """

    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    family = models.ForeignKey(Family, on_delete=models.CASCADE, related_name='users')
    picture = models.ImageField(_("Picture"), null=True, blank=True)
    head = models.OneToOneField(Family, null=True, related_name='familyhead', on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    def is_head_of_fmaily(self):
        if self.head == self.family:
            self.is_superuser = True
            self.save()
            return True
        return False

    def set_picture(self, picture_data):
        try:
            if picture_data is not None and all(
                    [picture_data.get("path", False), picture_data.get("filename", False)]
            ):
                with open(picture_data["path"], "rb") as f:
                    self.picture.save(picture_data["filename"], f)
        except FileNotFoundError:
            pass

accounts/forms.py
from allauth.account.forms import LoginForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from django import forms
from django.utils.translation import gettext_lazy as _

from accounts.models import Family

User = get_user_model()


class CustomUserEditForm(UserChangeForm):
    picture = forms.ImageField(label=_("Picture/Logo"), required=False)


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    picture = forms.ImageField(label=_("Picture/Logo"), required=False)
    family_name = forms.CharField(required=True, max_length=255)
    is_head = forms.BooleanField(required=True)
    error_css_class = "error"

    class Meta:
        model = User
        fields = ("username", "email", "picture", "password1", "password2", "family_name", "is_head")
        exclude = ("family", "head")

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)

        user.email = self.cleaned_data['email']
        family_name = self.cleaned_data['family_name']
        is_head = self.cleaned_data['is_head']
        family, created = Family.objects.get_or_create(family_name=family_name)
        user.family = family
        if is_head:
            user.head = family
        user.name = user.username
        if commit:
            if self.cleaned_data["password1"]:
                user.set_password(self.cleaned_data["password1"])
            user.save()
        return user

accounts/views.py
import json

from django.contrib import messages
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView
from django.db.models import Q

from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from django.views.generic.edit import CreateView
from django.contrib.auth import logout

from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.core.validators import validate_email
from accounts.forms import CustomUserCreationForm
from accounts.models import User, Family
from django.core.mail import send_mail, BadHeaderError




class UsernameValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        username = data['username']
        if any(char.isdigit() for char in username) or not str(username).isalnum():
            return JsonResponse({"username_error": "please Enter valid username."}, status=400)
        if User.objects.filter(username=username).exists():
            return JsonResponse({"username_error": "This username is already taken, please try another."}, status=400)

        return JsonResponse({"username_valid": True})


class UserEmailValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        email = data['email']
        try:
            validate_email(email)
        except:
            return JsonResponse({"email_error": "please Enter valid Email."}, status=400)
        if User.objects.filter(email=email).exists():
            return JsonResponse({"email_error": "This Email is already taken, please try another."}, status=400)

        return JsonResponse({"useremail_valid": True})


class UserFamilyValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        family_name = data['family_name']

        if any(char.isdigit() for char in family_name) or not str(family_name).isalnum():
            return JsonResponse({"family_name_error": "please enter a Valid family name"}, status=400)

        return JsonResponse({"userfamily_name_valid": True})


class UserHeadValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        print("momo")
        print(data)
        is_head = data['is_head']
        family_name = data['family_name']
        if not family_name:
            return JsonResponse({"family_name_error": "This cannot be empty, please add a family name"}, status=400)
        family = Family.objects.filter(family_name=family_name)
        if User.objects.filter(head=family).exists() and is_head:
            return JsonResponse({"family_name_error": "You Can not Be the head of this Family, because it's already "
                                                      "have one"}, status=400)

        return JsonResponse({"family_name_valid": True})


class PasswordValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        print("moomo")
        print(data)
        password1 = data['passwordone']
        password2 = data['password2']
        if password2 != password1:
            return JsonResponse({"password_error": "The two passwords doesn't match, please enter same password"},
                                status=400)

        return JsonResponse({"password_valid": True})


class RegisterView(CreateView):
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('login')
    form_class = CustomUserCreationForm
    success_message = _("Your profile was created successfully")

    def post(self, request, *args, **kwargs):
        family_name = request.POST['family_name']

        password1 = request.POST['password1']
        password2 = request.POST['password2']
        username = request.POST['username']
        picture = request.POST['picture']
        email = request.POST['email']
        is_head = ''
        try:
            is_head = request.POST['is_head']
        except:
            print("This is not the Head of Family")
        ctx = {
            'user': request.POST
        }
        family, created = Family.objects.get_or_create(family_name=family_name)
        if is_head and User.objects.filter(head=family).exists():
            messages.error(request, "You Can not Be the head of this Family, because it's already have one")
            return render(request, "accounts/register.html", context=ctx)

        if User.objects.filter(email=email).exists():
            messages.error(request, "This Email is already taken, please try another.")
            return render(request, "accounts/register.html", context=ctx)

        if User.objects.filter(username=username).exists():
            messages.error(request, "This Username is already taken, please try another.")
            return render(request, "accounts/register.html", context=ctx)

        if password2 != password1:
            messages.error(request, "The two passwords doesn't match, please enter same password")
            return render(request, "accounts/register.html", context=ctx)

        send_mail(
            'Welcoming Login Account Email',
            'You have registered in out site, login in here',
            'noreply@gmail.com',
            [request.POST['email']],

        )
        if is_head:
            user = User.objects.create_user(username=username, name=username, email=email, picture=picture,
                                            family=family, head=family)
        else:
            user = User.objects.create_user(username=username, name=username, email=email, picture=picture,
                                            family=family)
        user.set_password(password1)
        user.save()

        messages.success(request, self.success_message)

        return super(RegisterView, self).post(request, *args, **kwargs)


class UserLogin(LoginView):
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('expenses-dash:expenses')

    def post(self, request, *args, **kwargs):
        print(request.POST)
        print(self.get_form().errors)
        return super(UserLogin, self).post(request, *args, **kwargs)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse("account:login"))


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "accounts/password/password_reset_email.html"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="accounts/password/password_reset.html",
                  context={"password_reset_form": password_reset_form})

templates/accounts/login.html
{% extends 'base_auth.html' %}
{% load static i18n %}
{% block content %}

<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
          class="img-fluid" alt="Sample image">
      </div>


      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <form action="{% url 'account:login' %}" method="post">
            {% csrf_token %}
          <!-- username input -->
        {% include 'partials/_messages.html' %}

          <div class="form-outline mb-4">
            <input type="username" id="id_username" class="form-control form-control-lg" name="username" required
              placeholder="Enter Your Full Name" value="{{ user.username }}" />
            <label class="form-label" for="id_username">{% trans 'User Name' %}</label>


          <!-- Password input -->
          <div class="form-outline mb-3">
            <input type="password" id="id_password1" value="{{ user.password1 }}" class="form-control form-control-lg" name="password" required
              placeholder="Enter password" />
            <label class="form-label" for="id_password1">{% trans 'Password' %}</label>
          </div>

          <div class="text-center text-lg-start mt-4 pt-2">
            <button type="submit" class="btn btn-primary btn-lg"
              style="padding-left: 2.5rem; padding-right: 2.5rem;">{% trans 'Login' %}</button>
            <p class="small fw-bold mt-2 pt-1 mb-0">{% trans "You Don't have an account?" %} <a href="{% url "account:register" %}"
                class="link-danger">{% trans 'Register' %}</a></p>

                          <p class="small fw-bold mt-2 pt-1 mb-0">{% trans "You Don't Remember Your Password" %} <a href="{% url "account:password_reset" %}"
                class="link-danger">{% trans 'Reset Your Password Now' %}</a></p>
          </div>

        </form>
      </div>
    </div>
  </div>
  <div
    class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">

    <div class="text-white mb-3 mb-md-0">
     {% trans ' Copyright © 2020. All rights reserved.' %}
    </div>

  </div>
</section>
{#<script src="{% static "js/register.js" %}">#}

</script>
{% endblock %}

templates/accounts/register.html
{% extends 'base_auth.html' %}
{% load static i18n %}
{% block content %}

<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
          class="img-fluid" alt="Sample image">
      </div>


      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <form action="{% url 'account:register' %}" method="post" enctype="application/x-www-form-urlencoded">
            {% csrf_token %}
          <!-- username input -->
        {% include 'partials/_messages.html' %}
          <div class="form-outline mb-4">
            <input type="username" id="id_username" class="form-control form-control-lg" name="username" required
              placeholder="Enter Your Full Name" value="{{ user.username }}" />
            <label class="form-label" for="id_username">{% trans 'User Name' %}</label>


          </div>
            <div class="invalid-feedback" id="username_invalid_feedback"style="display:none">

            </div>
            <p class="text-sm text-success usernameSuccess" style="display:none"></p>
            <div class="form-outline mb-4">
            <input type="email" id="id_email" class="form-control form-control-lg" name="email" required
              placeholder="Enter a valid email address" value="{{ user.email }}" />
            <label class="form-label" for="id_email">{% trans 'Email address' %}</label>
          </div>
                <div class="invalid-feedback" id="email_invalid_feedback"style="display:none">
                </div>
                <p class="text-sm text-success userEmailSuccess"></p>
            <div class="form-outline mb-4">
            <input type="text" id="id_family" class="form-control form-control-lg" name="family_name" required
              placeholder="Enter your family Name" value="{{ user.family_name }}"/>
            <label class="form-label" for="id_family">{% trans 'Family Name' %}</label>
          </div>
                <div class="invalid-feedback" id="family_name_invalid_feedback"style="display:none">
                </div>
                <div class="form-check">
              <input class="form-check-input" type="checkbox" id="id_head" name="is_head" value="false">
              <label class="form-check-label" for="id_head">
          <h6>   Head of the family?</h6>
              </label>
            </div>
 <div class="invalid-feedback" id="is_head_invalid_feedback"style="display:none">
                </div>
            <br>
            <br>
                 <div class="form-outline mb-4">
            <input type="file" id="id_picture" value="{{ user.picture }}" class="form-control form-control-lg" name="picture" required
              placeholder="Add your Profile Picture" />
            <label class="form-label" for="id_picture">{% trans 'Profile Picture' %}</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-3">
            <input type="password" id="id_password1" value="{{ user.password1 }}" class="form-control form-control-lg" name="password1" required
              placeholder="Enter password" />
            <label class="form-label" for="id_password1">{% trans 'Password' %}</label>
          </div>


                   <div class="form-outline mb-3">
            <input type="password" id="id_password2" class="form-control form-control-lg" name="password2" required
              placeholder="ReEnter password" />
            <label class="form-label" for="id_password2">{% trans 'Password Confirmation' %}</label>
          </div>


         <div class="invalid-feedback" id="password_invalid_feedback"style="display:none">
         </div>

          <div class="text-center text-lg-start mt-4 pt-2">
            <button type="submit" class="btn btn-primary btn-lg"
              style="padding-left: 2.5rem; padding-right: 2.5rem;">{% trans 'Register' %}</button>
            <p class="small fw-bold mt-2 pt-1 mb-0">{% trans "You have already an account?" %} <a href="{% url "account:login" %}"
                class="link-danger">{% trans 'Login' %}</a></p>


          </div>

        </form>
      </div>
    </div>
  </div>
  <div
    class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">

    <div class="text-white mb-3 mb-md-0">
     {% trans ' Copyright © 2020. All rights reserved.' %}
    </div>

  </div>
</section>
<script src="{% static "js/register.js" %}">

</script>
{% endblock %}

templates/accounts/reset-password.html
{% extends 'base_auth.html' %}

{% block content %}
<div class="card">
<div class="card-body">


    <h1>Reset Password</h1>

</div>

</div>
{% endblock %}

templates/accounts/set-new-password.html
{% extends 'base_auth.html' %}

{% block content %}
<div class="card">
<div class="card-body">


    <h1>Set New Password</h1>

</div>

</div>
{% endblock %}