FamilyExpenses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('home/', include('expense.urls')),
    path('incomes/', include('income.urls')),
    path('accounts/', include('accounts.urls')),
    path('preferences/', include('userperferences.urls')),
    path('admin/', admin.site.urls),


    # Password Logic
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

income/urls.py
from django.urls import path

from income.views import IncomeListView, IncomeEditView, delete_income, IncomeCreateView

app_name = "income-dash"
urlpatterns = [

    # Expense
    path('', IncomeListView.as_view(), name='incomes'),
    path('add-income/', IncomeCreateView.as_view(), name='add_income'),
    path('edit-income/<int:pk>', IncomeEditView.as_view(), name='edit_income'),
    path('delete-income/<int:pk>', delete_income, name='delete_income'),
    ]

income/models.py
from django.db import models
from django.utils.timezone import now
from accounts.models import User


class Source(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Income(models.Model):
    amount = models.DecimalField(max_digits=8, decimal_places=3, null=False)
    date = models.DateField(default=now())
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)

    def __str__(self):
        return f"This income for{self.description} which belong to {self.owner.username}"

    class Meta:
        ordering: ['-date']

income/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.timezone import now

from income.models import Income, Source


class IncomeCreationForm(forms.ModelForm):
    amount = forms.DecimalField(decimal_places=3)

    class Meta:
        model = Income
        fields = (
            "amount",
            "source",
            "date",
            "description",
        )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(IncomeCreationForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        outlay = super(IncomeCreationForm, self).save(commit=False)

        outlay.price = self.cleaned_data['amount']
        outlay.description = self.cleaned_data['description']
        outlay.date = self.cleaned_data['date']
        outlay.outlay_type = Source.objects.filter(name=self.cleaned_data['source']).first()
        outlay.owner = self.user

        if commit:
            outlay.save()
        return outlay

    def clean_date(self):
        date = self.cleaned_data['date']
        if date > now().date():
            raise ValidationError("You can't choose date in Future")
        return date

    def clean_price(self):
        amount = self.cleaned_data['amount']
        if amount < 0:
            raise ValidationError("You can't choose a negative price")
        return amount

income/views.py
from braces.views import UserFormKwargsMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from income.forms import IncomeCreationForm
from income.models import Income, Source
from userperferences.models import UserPerference


class IncomeListView(ListView):
    template_name = "incomes/incomes.html"
    success_url = "income-dash:incomes"
    queryset = Income.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        incomes = self.queryset.filter(owner=self.request.user)
        paginator = Paginator(incomes, 5)
        page_number = self.request.GET.get('page')
        page_obj = Paginator.get_page(paginator, page_number)
        try:
            currency = UserPerference.objects.get(user=self.request.user).currency
        except:
            currency = None
        ctx = {
            'incomes': incomes,
            'page_obj': page_obj,
            'currency': currency
        }
        return ctx


class IncomeCreateView(LoginRequiredMixin, UserFormKwargsMixin, CreateView):
    template_name = "incomes/add_income.html"
    form_class = IncomeCreationForm

    def get_context_data(self, **kwargs):
        context = super(IncomeCreateView, self).get_context_data(**kwargs)
        sources = Source.objects.all()
        context['sources'] = sources
        context['values'] = self.request.POST
        return context

    def get_success_url(self):
        messages.success(self.request, 'Income Saved successfully')
        return reverse('income-dash:incomes')


class IncomeEditView(LoginRequiredMixin, UserFormKwargsMixin, UpdateView):
    template_name = "incomes/edit_income.html"
    model = Income
    form_class = IncomeCreationForm

    def get_context_data(self, **kwargs):
        context = super(IncomeEditView, self).get_context_data(**kwargs)
        sources = Source.objects.all()
        context['sources'] = sources
        return context

    def get_success_url(self):
        messages.success(self.request, 'Income Update successfully')
        return reverse('income-dash:incomes')


def delete_income(request, pk):
    expense = Income.objects.get(pk=pk)
    expense.delete()
    messages.success(request, 'Income has been deleted successfully')
    return redirect("income-dash:incomes")

templates/incomes/add_income.html
{% extends 'base.html' %}
{% load static i18n %}
<h1>{% block title %}
{% trans 'Add Income' %}

{% endblock %}
</h1>

{% block content  %}
<div class="container mt-4">
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'income-dash:incomes' %}">{% trans 'Incomes' %}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            {% trans 'Add Incomes' %}
        </li>
    </ol>
</nav>
</div>
<div class="card">
  <div class="card-body">
    <form action="{% url 'income-dash:add_income' %}" method="post">
        {% csrf_token %}
     {{ form.errors }}
    {% include 'partials/_messages.html'  %}
        <div class="form-group" style="margin-bottom: 15px">
            <label for="">{% trans "Amount" %}</label>
            <input type="number" class="form-control form-control-sm" name="amount" value="{{ values.amount }}">

        </div>
        <div class="form-group"  style="margin-bottom: 15px">
            <label for="">{% trans "Source" %}</label>
            <select class="form-control" name="source">
                {% for source in sources %}
                <option name="outlay_type" value="{{ source.pk }}">
                    {{ source.name }}
                </option>
                {% endfor %}
            </select>

        </div>

        <div class="form-group"  style="margin-bottom: 15px">
            <label for="">{% trans "Description" %}</label>
            <input type="text" class="form-control form-control-sm" name="description" value="{{ values.description }}">
        </div>
        <div class="form-group" style="margin-bottom: 15px">
            <label for="">{% trans "Date" %}</label>
            <input type="date" class="form-control form-control-sm" name="date" value="{{ values.date  }}">

        </div>

        <input  style="margin-top: 15px" type="submit" value="Submit" class="btn btn-primary btn-primary-sm">
        </form>
    </div>
</div>
{% endblock %}

templates/incomes/edit_income.html
{% extends 'base.html' %}
{% load static i18n %}
<h1>{% block title %}
{% trans 'Edit Incomes' %}

{% endblock %}
</h1>

{% block content  %}
<div class="container mt-4">
<div class="row">
    <div class="col-md-10">
        <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'income-dash:incomes' %}">{% trans 'Incomes' %}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            {% trans 'Edit Incomes' %}
        </li>
    </ol>
</nav>
    </div>
        <div class="col-md-2">
                     <a href="{% url "income-dash:delete_income" object.id %}" class="btn btn-danger btn-sm">
             {% trans "Delete" %}</a>
    </div>
</div>

</div>

<div class="card">
  <div class="card-body">
    <form action="{% url "income-dash:edit_income" object.pk %}" method="post">
        {% csrf_token %}
    {% include 'partials/_messages.html'  %}
         {{ form.errors }}
        <div class="form-group" style="margin-bottom: 15px">
            <label for="">{% trans "Amount" %}</label>
            <input type="number" class="form-control form-control-sm" name="amount" value="{{object.amount}}">

        </div>
        <div class="form-group"  style="margin-bottom: 15px">
            <label for="">{% trans "Source" %}</label>
            <select class="form-control" name="source">
           <option name="source" selected value="{{ object.source.pk }}">
                    {{ object.source }}
                </option>
                {% for source in sources %}
                <option name="source" value="{{ source.pk }}">
                    {{ source.name }}
                </option>
                {% endfor %}
            </select>

        </div>

        <div class="form-group"  style="margin-bottom: 15px">
            <label for="">{% trans "Description" %}</label>
            <input type="text" class="form-control form-control-sm" name="description" value="{{ object.description }}">

        </div>
        <div class="form-group" style="margin-bottom: 15px">
            <label for="">{% trans "Date" %}</label>
            <input type="date" class="form-control form-control-sm" name="date" value="{{ object.date |date:'Y-m-d' }}">

        </div>

        <input  style="margin-top: 15px" type="submit" value="Save" class="btn btn-primary btn-primary-sm">
        </form>
    </div>
</div>
{% endblock %}

templates/incomes/incomes.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
<h1>{% trans 'Incomes List' %}</h1>
{% endblock %}

{% block content  %}
<div class="container" mt-4>

<div class="row">
    <div class="col-md-10" style="position: inherit">
        <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url "income-dash:incomes" %}">{% trans 'Incomes' %}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            {% trans 'MY Incomes' %}
        </li>
    </ol>
</nav>
        </div>
    <div class="col-md-2">
        <a href="{% url 'income-dash:add_income' %}"
           class="btn btn-primary">{% trans 'Add Incomes' %}</a>
    </div>
</div>
    <br/>
<div class="container">
    {% include 'partials/_messages.html' %}
    {% if incomes.count %}

   <div class="app-table">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
             <th>{% trans "Amount (CURRENCY is :  " %} {{ currency }} )</th>
           <th>{% trans "Source" %}</th>
           <th>{% trans "Description" %}</th>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Delete" %}</th>
            <th>{% trans "Edit" %}</th>

        </tr>
        </thead>
        <tbody>
        {% for income in page_obj %}
        <tr>
            <td>
                {{ income.amount }}
            </td>
            <td>
                {{ income.source }}
            </td>

            <td>
               {{  income.description }}
            </td>
            <td>
                {{ income.date }}
            </td>
                     <th><a id='delete'href="{% url "income-dash:delete_income" income.id %}" class="btn btn-danger btn-sm">
             {% trans "Delete" %}</a> </th>
         <th><a id="edit" href="{% url "income-dash:edit_income" income.id %}" class="btn btn-secondary btn-sm">
             {% trans "Edit" %}</a> </th>

        </tr>
        {% endfor %}
        </tbody>
    </table>
   </div>
   <div class="pagination-container">


        <div class="">
        {% trans 'Showing page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}
        </div>
    <ul class="pagination align-right float-right mr-auto">
    {% if page_obj.has_previous %}
        <li {% if page_obj.number == 1 %} class="page-item active"{% endif %}>
        <a class="page-link" href="?page=1">&laquo; {% trans '1' %}</a>
        </li>
            <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
        </li>
    {% endif %}
        {% if page_obj.has_next %}
         <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
        </li>
            <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}  &raquo;</a>
        </li>
            {% endif %}
    </ul>
    {% else %}

    </div>
   <h5>{% trans "You don't have any Incomes yet, Find a job" %}</h5>
   {% endif %}
</div>
</div>

{% endblock %}