FamilyExpenses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('home/', include('expense.urls')),
    path('incomes/', include('income.urls')),
    path('accounts/', include('accounts.urls')),
    path('preferences/', include('userperferences.urls')),
    path('admin/', admin.site.urls),


    # Password Logic
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expense/urls.py
from django.urls import path

from expense.views import delete_expense, ExpenseCreateView, ExpenseEditView, search_expenses, \
    MaterialCreateView, ExpenseListView, MaterialListView, MaterialEditView, delete_material, OutlayTypeListView, \
    OutlayTypeCreateView, OutlayTypeEditView, delete_outlaytype, UserListView, UserCreateView, ExpensesChartList
from django.views.decorators.csrf import csrf_exempt

app_name = "expenses-dash"
urlpatterns = [

    # Expense
    path('', ExpenseListView.as_view(), name='expenses'),
    path('search-expenses', csrf_exempt(search_expenses), name='search_expenses'),
    path('add-expense/', ExpenseCreateView.as_view(), name='add_expense'),
    path('edit-expense/<int:pk>', ExpenseEditView.as_view(), name='edit_expense'),
    path('delete-expense/<int:pk>', delete_expense, name='delete_expense'),

    # Materials
    path('materials/', MaterialListView.as_view(), name='materials'),
    path('add-material/', MaterialCreateView.as_view(), name='add_material'),
    path('edit-material/<int:pk>', MaterialEditView.as_view(), name='edit_material'),
    path('delete-material/<int:pk>', delete_material, name='delete_material'),

    # Outlay Types
    path('outlaytypes/', OutlayTypeListView.as_view(), name='outlaytypes'),
    path('add-outlaytype/', OutlayTypeCreateView.as_view(), name='add_outlaytype'),
    path('edit-outlaytype/<int:pk>', OutlayTypeEditView.as_view(), name='edit_outlaytype'),
    path('delete-outlaytypes/<int:pk>', delete_outlaytype, name='delete_outlaytype'),

    # User
    path('users/', UserListView.as_view(), name='users'),
    path('add-user/', UserCreateView.as_view(), name='add_user'),
    # path('edit-outlaytype/<int:pk>', OutlayTypeEditView.as_view(), name='edit_outlaytype'),

    # Chart
    path("expenses-chart-list/", ExpensesChartList.as_view(), name="export_pdf"),

]

income/urls.py
from django.urls import path

from income.views import IncomeListView, IncomeEditView, delete_income, IncomeCreateView

app_name = "income-dash"
urlpatterns = [

    # Expense
    path('', IncomeListView.as_view(), name='incomes'),
    path('add-income/', IncomeCreateView.as_view(), name='add_income'),
    path('edit-income/<int:pk>', IncomeEditView.as_view(), name='edit_income'),
    path('delete-income/<int:pk>', delete_income, name='delete_income'),
    ]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class Family(models.Model):
    """ Family Model """
    family_name = models.CharField(_("Name of Family Name"), blank=True, max_length=255, unique=True)


class User(AbstractUser):
    """ Custom User Model """

    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    family = models.ForeignKey(Family, on_delete=models.CASCADE, related_name='users')
    picture = models.ImageField(_("Picture"), null=True, blank=True)
    head = models.OneToOneField(Family, null=True, related_name='familyhead', on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    def is_head_of_fmaily(self):
        if self.head == self.family:
            self.is_superuser = True
            self.save()
            return True
        return False

    def set_picture(self, picture_data):
        try:
            if picture_data is not None and all(
                    [picture_data.get("path", False), picture_data.get("filename", False)]
            ):
                with open(picture_data["path"], "rb") as f:
                    self.picture.save(picture_data["filename"], f)
        except FileNotFoundError:
            pass

expense/models.py
from django.db import models
from django.utils.timezone import now

from accounts.models import User


class Material(models.Model):
    name = models.CharField(max_length=255, unique=True)
    is_service = models.BooleanField()
    description = models.TextField()

    def __str__(self):
        return self.name


class OutlayType(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name


class Outlay(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    outlay_type = models.ForeignKey(OutlayType, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=3, null=False)
    date = models.DateField(default=now(), null=False)
    description = models.TextField()

    def __str__(self):
        return f"This Expense for{self.description} which belong to {self.owner.username} with amount {self.price}"

    class Meta:
        ordering: ['-date']

accounts/forms.py
from allauth.account.forms import LoginForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from django import forms
from django.utils.translation import gettext_lazy as _

from accounts.models import Family

User = get_user_model()


class CustomUserEditForm(UserChangeForm):
    picture = forms.ImageField(label=_("Picture/Logo"), required=False)


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    picture = forms.ImageField(label=_("Picture/Logo"), required=False)
    family_name = forms.CharField(required=True, max_length=255)
    is_head = forms.BooleanField(required=True)
    error_css_class = "error"

    class Meta:
        model = User
        fields = ("username", "email", "picture", "password1", "password2", "family_name", "is_head")
        exclude = ("family", "head")

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)

        user.email = self.cleaned_data['email']
        family_name = self.cleaned_data['family_name']
        is_head = self.cleaned_data['is_head']
        family, created = Family.objects.get_or_create(family_name=family_name)
        user.family = family
        if is_head:
            user.head = family
        user.name = user.username
        if commit:
            if self.cleaned_data["password1"]:
                user.set_password(self.cleaned_data["password1"])
            user.save()
        return user

expense/views.py
import datetime

from braces.views import UserFormKwargsMixin, LoginRequiredMixin
from django.contrib import messages
from django.db.models import Sum, Q

from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView
from rest_framework import generics
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.forms import CustomUserCreationForm
from accounts.models import User, Family
from datetime import datetime as dt
from dateutil.relativedelta import relativedelta
from expense.forms import OutlayCreationForm, MaterialCreationForm, OutlayTypeCreationForm
from expense.models import OutlayType, Material, Outlay
from django.core.paginator import Paginator

import json
from django.http import JsonResponse

from expense.serializers import OutlaySerializer
from userperferences.models import UserPerference


def search_expenses(request):
    if request.method == 'POST':
        search_string = json.loads(request.body).get('searchText')
        expense = Outlay.objects.filter(
            price__istartswith=search_string,
            owner=request.user
        ) | Outlay.objects.filter(
            date__istartswith=search_string,
            owner=request.user
        ) | Outlay.objects.filter(
            description__icontains=search_string,
            owner=request.user
        ) | Outlay.objects.filter(
            outlay_type__name__icontains=search_string,
            owner=request.user
        ) | Outlay.objects.filter(
            material__name__icontains=search_string,
            owner=request.user
        )
        data = expense.values()

    return JsonResponse(list(data), safe=False)


class ExpenseListView(ListView):
    template_name = "expenses/expenses.html"
    success_url = 'expenses-dash:expenses'
    queryset = Outlay.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        expenses = self.queryset.filter(owner=self.request.user)
        paginator = Paginator(expenses, 5)
        page_number = self.request.GET.get('page')
        page_obj = Paginator.get_page(paginator, page_number)
        try:
            currency = UserPerference.objects.get(user=self.request.user).currency
        except:
            currency = None
        ctx = {
            'outlays': expenses,
            'page_obj': page_obj,
            'currency': currency
        }
        return ctx


class ExpenseCreateView(LoginRequiredMixin, UserFormKwargsMixin, CreateView):
    template_name = "expenses/add_expense.html"
    success_url = 'expenses-dash:expenses'
    form_class = OutlayCreationForm

    def get_context_data(self, **kwargs):
        context = super(ExpenseCreateView, self).get_context_data(**kwargs)
        outlay_types = OutlayType.objects.all()
        materials = Material.objects.all()
        context['outlay_types'] = outlay_types
        context['materials'] = materials
        context['values'] = self.request.POST
        return context

    def get_success_url(self):
        messages.success(self.request, 'Outlay Saved successfully')
        return reverse('expenses-dash:expenses')


class ExpenseEditView(LoginRequiredMixin, UserFormKwargsMixin, UpdateView):
    template_name = "expenses/edit_expense.html"
    model = Outlay
    form_class = OutlayCreationForm

    def get_context_data(self, **kwargs):
        context = super(ExpenseEditView, self).get_context_data(**kwargs)
        outlay_types = OutlayType.objects.all()
        materials = Material.objects.all()
        context['outlay_types'] = outlay_types
        context['materials'] = materials
        return context

    def get_success_url(self):
        messages.success(self.request, 'Outlay Update successfully')
        return reverse('expenses-dash:expenses')


def delete_expense(request, pk):
    expense = Outlay.objects.get(pk=pk)
    expense.delete()
    messages.success(request, 'Outlay has been deleted successfully')
    return redirect("expenses-dash:expenses")


class OutlayTypeListView(ListView):
    template_name = "expenses/outlaytype.html"
    success_url = 'expenses-dash:outlaytypes'
    queryset = OutlayType.objects.all()

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_head_of_fmaily():
            messages.error(request, "You are not the head of the Family So you can't see/add or edit any materials")
            return render(request, "expenses/expenses.html")
        return super(OutlayTypeListView, self).get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        outlaytypes = self.queryset
        paginator = Paginator(outlaytypes, 5)
        page_number = self.request.GET.get('page')
        page_obj = Paginator.get_page(paginator, page_number)
        ctx = {
            'outlaytypes': outlaytypes,
            'page_obj': page_obj
        }
        return ctx


class OutlayTypeCreateView(LoginRequiredMixin, CreateView):
    template_name = "expenses/add_outlaytype.html"
    form_class = OutlayTypeCreationForm
    success_url = reverse_lazy("expenses-dash:outlaytypes")

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_head_of_fmaily():
            messages.error(request, "You are not the head of the Family So you can't see/add or edit any materials")
            return render(request, "expenses/expenses.html")
        return super(OutlayTypeCreateView, self).get(request, *args, **kwargs)


class OutlayTypeEditView(LoginRequiredMixin, UpdateView):
    template_name = "expenses/edit_outlaytype.html"
    form_class = OutlayTypeCreationForm
    success_url = reverse_lazy("expenses-dash:outlaytypes")
    queryset = OutlayType.objects.all()

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_head_of_fmaily():
            messages.error(request, "You are not the head of the Family So you can't see/add or edit any materials")
            return render(request, "expenses/expenses.html")
        return super(OutlayTypeEditView, self).get(request, *args, **kwargs)


def delete_outlaytype(request, pk):
    material = OutlayType.objects.get(pk=pk)
    material.delete()
    messages.success(request, 'OutlayType has been deleted successfully')
    return redirect("expenses-dash:outlaytypes")


class MaterialListView(ListView):
    template_name = "expenses/materials.html"
    success_url = 'expenses-dash:materials'
    queryset = Material.objects.all()

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_head_of_fmaily():
            messages.error(request, "You are not the head of the Family So you can't see/add or edit any materials")
            return render(request, "expenses/expenses.html")
        return super(MaterialListView, self).get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        materials = self.queryset
        paginator = Paginator(materials, 5)
        page_number = self.request.GET.get('page')
        page_obj = Paginator.get_page(paginator, page_number)
        ctx = {
            'materials': materials,
            'page_obj': page_obj
        }
        return ctx


class MaterialCreateView(LoginRequiredMixin, CreateView):
    template_name = "expenses/add_material.html"
    form_class = MaterialCreationForm
    success_url = reverse_lazy("expenses-dash:materials")

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_head_of_fmaily():
            messages.error(request, "You are not the head of the Family So you can't see/add or edit any materials")
            return render(request, "expenses/expenses.html")
        return super(MaterialCreateView, self).get(request, *args, **kwargs)


class MaterialEditView(LoginRequiredMixin, UpdateView):
    template_name = "expenses/edit_materials.html"
    form_class = MaterialCreationForm
    success_url = reverse_lazy("expenses-dash:materials")
    queryset = Material.objects.all()

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_head_of_fmaily():
            messages.error(request, "You are not the head of the Family So you can't see/add or edit any materials")
            return render(request, "expenses/expenses.html")
        return super(MaterialEditView, self).get(request, *args, **kwargs)


def delete_material(request, pk):
    material = Material.objects.get(pk=pk)
    material.delete()
    messages.success(request, 'Material has been deleted successfully')
    return redirect("expenses-dash:materials")


class UserListView(ListView):
    template_name = "expenses/users.html"
    success_url = 'expenses-dash:users'
    queryset = User.objects.all()

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_head_of_fmaily():
            messages.error(request, "You are not the head of the Family So you can't see/add or edit any materials")
            return render(request, "expenses/expenses.html")
        return super(UserListView, self).get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        users = self.queryset
        paginator = Paginator(users, 5)
        page_number = self.request.GET.get('page')
        page_obj = Paginator.get_page(paginator, page_number)
        ctx = {
            'users': users,
            'page_obj': page_obj
        }
        return ctx


class UserCreateView(CreateView):
    template_name = 'expenses/add_user.html'
    success_url = reverse_lazy('expenses-dash:users')
    success_message = "User profile has been created successfully"
    form_class = CustomUserCreationForm

    def post(self, request, *args, **kwargs):
        family_name = request.POST['family_name']

templates/expenses/add_user.html
{% extends 'base.html' %}
{% load static i18n %}
<h1>{% block title %}
{% trans 'Add Expense' %}

{% endblock %}
</h1>

{% block content  %}
<div class="container mt-4">
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'expenses-dash:expenses' %}">{% trans 'Epenses' %}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            {% trans 'Add Expenses' %}
        </li>
    </ol>
</nav>
</div>
<div class="card">
  <div class="card-body">
   <form action="{% url 'expenses-dash:add_user' %}" method="post" enctype="application/x-www-form-urlencoded">
            {% csrf_token %}
       {{ form.errors }}
          <!-- username input -->
        {% include 'partials/_messages.html' %}
          <div class="form-outline mb-4">
            <input type="username" id="id_username" class="form-control form-control-lg" name="username" required
              placeholder="Enter Your Full Name"  />
            <label class="form-label" for="id_username">{% trans 'User Name' %}</label>


          </div>
            <div class="invalid-feedback" id="username_invalid_feedback"style="display:none">

            </div>
            <p class="text-sm text-success usernameSuccess" style="display:none"></p>
            <div class="form-outline mb-4">
            <input type="email" id="id_email" class="form-control form-control-lg" name="email" required
              placeholder="Enter a valid email address" />
            <label class="form-label" for="id_email">{% trans 'Email address' %}</label>
          </div>
                <div class="invalid-feedback" id="email_invalid_feedback"style="display:none">
                </div>
                <p class="text-sm text-success userEmailSuccess"></p>
            <div class="form-outline mb-4">
            <input type="text" id="id_family" class="form-control form-control-lg" name="family_name" required
              placeholder="Enter your family Name" />
            <label class="form-label" for="id_family">{% trans 'Family Name' %}</label>
          </div>
                <div class="invalid-feedback" id="family_name_invalid_feedback"style="display:none">
                </div>
                <div class="form-check">
              <input class="form-check-input" type="checkbox" id="id_head" name="is_head" value="false">
              <label class="form-check-label" for="id_head">
          <h6>   Head of the family?</h6>
              </label>
            </div>
 <div class="invalid-feedback" id="is_head_invalid_feedback"style="display:none">
                </div>
            <br>
            <br>
                 <div class="form-outline mb-4">
            <input type="file" id="id_picture" class="form-control form-control-lg" name="picture" required
              placeholder="Add your Profile Picture" />
            <label class="form-label" for="id_picture">{% trans 'Profile Picture' %}</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-3">
            <input type="password" id="id_password1" class="form-control form-control-lg" name="password1" required
              placeholder="Enter password" />
            <label class="form-label" for="id_password1">{% trans 'Password' %}</label>
          </div>


                   <div class="form-outline mb-3">
            <input type="password" id="id_password2" class="form-control form-control-lg" name="password2" required
              placeholder="ReEnter password" />
            <label class="form-label" for="id_password2">{% trans 'Password Confirmation' %}</label>
          </div>


         <div class="invalid-feedback" id="password_invalid_feedback"style="display:none">
         </div>

          <div class="text-center text-lg-start mt-4 pt-2">
            <button type="submit" class="btn btn-primary btn-lg"
              style="padding-left: 2.5rem; padding-right: 2.5rem;">{% trans 'Add User' %}</button>
          </div>

        </form>
    </div>
</div>
{% endblock %}

templates/expenses/expenses.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
<h1>{% trans 'Expense List' %}</h1>
{% endblock %}

{% block content  %}

                <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">

            <div class="form-group">
               <input h type="text" class="form-control" id="id_month" placeholder="Enter Month Number"/>
                <br/>
                <br/>
                  <a href="{% url 'expenses-dash:export_pdf' %}"
        button type="button" class="btn btn-sm btn-outline-secondary form-control" id="month_id">{% trans 'Genrate Month Report' %}</a>
            </div>
         <div class="form-group">

 <input type="text" class="form-control" id="id_year" placeholder="Enter Year Number" />
             <br>
             <br>
                       <a href="{% url 'expenses-dash:export_pdf' %}"
        button type="button" class="btn btn-sm btn-outline-secondary form-control " id="year_id">{% trans 'Genrate Year Report' %}</a>
            </div>


          </div>
        </div>


<div class="container" mt-4>

<div class="row">
    <div class="col-md-10" style="position: inherit">
        <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url "expenses-dash:expenses" %}">{% trans 'Epenses' %}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            {% trans 'MY Expenses' %}
        </li>
    </ol>
</nav>
        </div>
    <div class="col-md-2">
        <a href="{% url 'expenses-dash:add_expense' %}"
           class="btn btn-primary">{% trans 'Add Expenses' %}</a>
    </div>
</div>
    <br/>
<div class="container">
    {% include 'partials/_messages.html' %}
    {% if outlays.count %}
        <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-4">
            <div class="form-group">
               <input type="text" class="form-control" id="id_search" placeholder="Search"/>
            </div>

        </div>
        </div>
   <div class="app-table">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
             <th>{% trans "Price (CURRENCY is :  " %} {{ currency }} )</th>
           <th>{% trans "Outlay Type" %}</th>
           <th>{% trans "Material" %}</th>
           <th>{% trans "Description" %}</th>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Delete" %}</th>
            <th>{% trans "Edit" %}</th>

        </tr>
        </thead>
        <tbody>
        {% for outlay in page_obj %}
        <tr>
            <td>
                {{ outlay.price }}
            </td>
            <td>
                {{ outlay.outlay_type }}
            </td>
            <td>
                {{ outlay.material }}
            </td>
            <td>
               {{  outlay.description }}
            </td>
            <td>
                {{ outlay.date }}
            </td>
                     <th><a id='delete'href="{% url "expenses-dash:delete_expense" outlay.id %}" class="btn btn-danger btn-sm">
             {% trans "Delete" %}</a> </th>
         <th><a id="edit" href="{% url "expenses-dash:edit_expense" outlay.id %}" class="btn btn-secondary btn-sm">
             {% trans "Edit" %}</a> </th>

        </tr>
        {% endfor %}
        </tbody>
    </table>
   </div>
   <div class="table-output">
            <table class="table table-striped table-hover">
        <thead>
        <tr>
           <th>{% trans "Price (CURRENCY is : " %} {{ currency }} )</th>
           <th>{% trans "Outlay Type" %}</th>
           <th>{% trans "Material" %}</th>
           <th>{% trans "Description" %}</th>
            <th>{% trans "Date" %}</th>


        </tr>
        </thead>
        <tbody class="table-body">

        </tbody>
    </table>
        </div>
   <div class="pagination-container">


        <div class="">
        {% trans 'Showing page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}
        </div>
    <ul class="pagination align-right float-right mr-auto">
    {% if page_obj.has_previous %}
        <li {% if page_obj.number == 1 %} class="page-item active"{% endif %}>
        <a class="page-link" href="?page=1">&laquo; {% trans '1' %}</a>
        </li>
            <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
        </li>
    {% endif %}
        {% if page_obj.has_next %}
         <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
        </li>
            <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}  &raquo;</a>
        </li>
            {% endif %}
    </ul>
    {% else %}

    </div>
   <h5>{% trans "You don't have any outlays yet" %}</h5>
   {% endif %}
</div>
</div>
    <script src="{% static "js/searchOutlays.js" %}"></script>
    <script>


  document.querySelector("#id_year").addEventListener("input", function(){

      let year =  document.querySelector("#id_year").value;
      let button =   document.querySelector('#year_id')
      let newHref = button.href.slice(0, button.href.lastIndexOf('/'))+ `/?year=${year}`
      button.href= newHref

  });
  document.querySelector("#id_month").addEventListener("input", function(){

      let month =  document.querySelector("#id_month").value;
      let button =   document.querySelector('#month_id')
      let newHref = button.href.slice(0, button.href.lastIndexOf('/'))+ `/?month=${month}`
      button.href= newHref

  });
</script>
{% endblock %}

templates/expenses/materials.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
<h1>{% trans 'Expense List' %}</h1>
{% endblock %}

{% block content  %}
<div class="container" mt-4>

<div class="row">
    <div class="col-md-10" style="position: inherit">
        <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url "expenses-dash:materials" %}">{% trans 'Materials' %}</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            {% trans 'All Materials' %}
        </li>
    </ol>
</nav>
        </div>
    <div class="col-md-2">
        <a href="{% url 'expenses-dash:add_material' %}"
           class="btn btn-primary">{% trans 'Add Material' %}</a>
    </div>
</div>
    <br/>
<div class="container">
    {% include 'partials/_messages.html' %}
    {% if materials.count %}

   <div class="app-table">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
           <th>{% trans "Name" %}</th>
           <th>{% trans "Is Service" %}</th>
           <th>{% trans "Description" %}</th>
            <th>{% trans "Delete" %}</th>
            <th>{% trans "Edit" %}</th>

        </tr>
        </thead>
        <tbody>

        {% for material in page_obj %}
        <tr>
            <td>
                {{ material.name }}
            </td>
            <td>
                {{ material.is_service }}
            </td>
            <td>
               {{  material.description }}
            </td>

                     <th><a id='delete'href="{% url "expenses-dash:delete_material" material.id %}" class="btn btn-danger btn-sm">
             {% trans "Delete" %}</a> </th>
         <th><a id="edit" href="{% url "expenses-dash:edit_material" material.id %}" class="btn btn-secondary btn-sm">
             {% trans "Edit" %}</a> </th>

        </tr>
        {% endfor %}
        </tbody>
    </table>
   </div>
   <div class="pagination-container">


        <div class="">
        {% trans 'Showing page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}
        </div>
    <ul class="pagination align-right float-right mr-auto">
    {% if page_obj.has_previous %}
        <li {% if page_obj.number == 1 %} class="page-item active"{% endif %}>
        <a class="page-link" href="?page=1">&laquo; {% trans '1' %}</a>
        </li>
            <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
        </li>
    {% endif %}
        {% if page_obj.has_next %}
         <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
        </li>
            <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}  &raquo;</a>
        </li>
            {% endif %}
    </ul>
    {% else %}

    </div>
   <h5>{% trans "You don't have any Materials yet" %}</h5>
   {% endif %}
</div>
</div>
<script src="{% static "js/searchOutlays.js" %}">

</script>
{% endblock %}